load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "helpers",
    srcs = ["helpers.py"],
    deps = [
        "//hyperon_das_atomdb:database",
    ],
)

