load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "process_helper",
    srcs = [],
    hdrs = ["process_helper.h"],
    includes = ["."],
    deps = [
    ],
)

cc_library(
    name = "test_helper",
    srcs = [],
    hdrs = ["test_helper.h"],
    includes = ["."],
    deps = [
    ],
)
