package(default_visibility = ["//visibility:public"])

cc_library(
    name = "link_creation_agent_lib",
    srcs = glob([ "*.cc"]),
    hdrs = glob(["*.h"]),
    includes = ["."],
    deps = [
        "//distributed_algorithm_node:distributed_algorithm_node_lib",
        "//query_engine:query_engine_lib",
    ],
)
