# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import src.grpc.common_pb2 as common__pb2
import src.grpc.atom_space_node_pb2 as atom__space__node__pb2


GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in atom_space_node_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AtomSpaceNodeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ping = channel.unary_unary(
            '/dasproto.AtomSpaceNode/ping',
            request_serializer=common__pb2.Empty.SerializeToString,
            response_deserializer=common__pb2.Ack.FromString,
            _registered_method=True
        )
        self.execute_message = channel.unary_unary(
            '/dasproto.AtomSpaceNode/execute_message',
            request_serializer=atom__space__node__pb2.MessageData.SerializeToString,
            response_deserializer=common__pb2.Empty.FromString,
            _registered_method=True
        )


class AtomSpaceNodeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def execute_message(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AtomSpaceNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'ping': grpc.unary_unary_rpc_method_handler(
            servicer.ping,
            request_deserializer=common__pb2.Empty.FromString,
            response_serializer=common__pb2.Ack.SerializeToString,
        ),
        'execute_message': grpc.unary_unary_rpc_method_handler(
            servicer.execute_message,
            request_deserializer=atom__space__node__pb2.MessageData.FromString,
            response_serializer=common__pb2.Empty.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler('dasproto.AtomSpaceNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dasproto.AtomSpaceNode', rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class AtomSpaceNode(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dasproto.AtomSpaceNode/ping',
            common__pb2.Empty.SerializeToString,
            common__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def execute_message(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dasproto.AtomSpaceNode/execute_message',
            atom__space__node__pb2.MessageData.SerializeToString,
            common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
