package(default_visibility = ["//visibility:public"])

cc_library(
    name = "commons_lib",
    srcs = [
        "Utils.cc",
        "SharedQueue.cc",
        "Stoppable.cc",
        "StoppableThread.cc",
    ],
    hdrs = [
        "Utils.h",
        "SharedQueue.h",
        "Stoppable.h",
        "StoppableThread.h",
        "Logger.h",
        "RequestValidator.h",
    ],
    includes = ["."],
    deps = [],
)
