load("@rules_cc//cc:cc_test.bzl", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "test_commons",
    srcs = ["TestConfig.cc"],
    hdrs = ["TestConfig.h"],
    includes = ["."],
)
