package(default_visibility = ["//visibility:public"])

cc_library(
    name = "Evolution_lib",
    srcs = ["Evolution.cc"],
    hdrs = ["Evolution.h"],
    includes = ["."],
    deps = [
        "//service_bus:service_bus_lib",
        "//commons:commons_lib",
    ],
)
