# TODO: merge `utils` and `commons` (https://github.com/singnet/das/issues/181)

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "commons_lib",
    srcs = glob(["*.cc"]),
    hdrs = glob(["*.h"]),
    includes = ["."],
    deps = [
    ],
)
