#pragma once

#include <set>
#include <string>

#include "QueryAnswer.h"

using namespace std;
using namespace query_engine;

namespace link_creators {

/**
 * Statistics regarding how many links has been actually created or updated by one
 * single call to LinkCreator::create().
 */
class LinkCreationStats {
    public:
        /**
         * Empty constructor.
         */
        LinkCreationStats() : visited(false), created(0), updated(0) {}

        /**
         * Constructor
         */
        LinkCreationStats(bool visited, unsigned int created, unsigned int updated) : visited(visited), created(created), updated(updated) {}

        // Inside LinkCreator::create(), handles are picked up from the passed query answer
        // in order to create or update links. In a single round of link creation, it may happen
        // that two different query answers produce the exact same group of handles so the
        // LinkCreator doesn't need to visit the same handle group again (visiting a group
        // of handles to create links is potentially an expensive operation). LinkCreator keeps
        // track of already visited groups of handles so `visited` is a bool that indicates
        // if the group of handles generated by the passed query answer has actually been
        // visited.
        bool visited;

        // How many links have actually been created in LinkCreator::create().
        unsigned int created;

        // How many links have actually been updated in LinkCreator::create().
        unsigned int updated;
};

/**
 * Processes a QueryAnswer and creates one or more links using any of the elements in it.
 * LinkCreator is NOT a thread-safe object.
 */
class LinkCreator {
   public:

    /**
     * Empty constructor.
     */
    LinkCreator() : _context("") {}

    /**
     * Empty destructor.
     */
    virtual ~LinkCreator() {}

    /**
     * Create or update one or more links using the passed QueryAnswer. A LinkCreationStats object is returned
     * with relevant statistics about how many links have actually been created or updated.
     *
     * @param query_answer The QueryAnswer object used to build link(s).
     * @return A LinkCreationStats object with statistics regarding link creation.
     */
    virtual LinkCreationStats create(shared_ptr<QueryAnswer> query_answer) = 0;

    /**
     * Return the AttentionBroker context to be used.
     *
     * @return the AttentionBroker context to be used.
     */
    inline const string& context() { return this->_context; }

    /**
     * Setter for the context to be used in AttentionBroker.
     *
     * @param context The AttentionBroker context.
     */
    inline void set_context(const string& context) { this->_context = context; }

    /**
     * Reset the structure that keeps track of already visited groups of handles.
     *
     * Visited keys are kept to avoid the attempt to create links for parameters (obtained from
     * QueryAnswer objects) that have already been seen. This is because the mere fact of trying
     * to create these links can be an expensive operation so we don't want to waste time
     * creating links just to discover later on that they have already been inserted into the
     * AtomDB.
     */
    void reset_visited() { this->_visited.clear(); }

   protected:

    inline void visit(const string& key) {
        this->_visited.insert(key);
    }

    inline bool visited(const string& key) {
        return (this->_visited.find(key) != this->_visited.end());
    }

   private:
    set<string> _visited;
    string _context;
};

}  // namespace link_creators
