# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: atom_space_node.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'atom_space_node.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61tom_space_node.proto\x12\x08\x64\x61sproto\x1a\x0c\x63ommon.proto\"n\n\x0bMessageData\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x03(\t\x12\x0e\n\x06sender\x18\x03 \x01(\t\x12\x14\n\x0cis_broadcast\x18\x04 \x01(\x08\x12\x1a\n\x12visited_recipients\x18\x05 \x03(\t2v\n\rAtomSpaceNode\x12(\n\x04ping\x12\x0f.dasproto.Empty\x1a\r.dasproto.Ack\"\x00\x12;\n\x0f\x65xecute_message\x12\x15.dasproto.MessageData\x1a\x0f.dasproto.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'atom_space_node_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEDATA']._serialized_start=49
  _globals['_MESSAGEDATA']._serialized_end=159
  _globals['_ATOMSPACENODE']._serialized_start=161
  _globals['_ATOMSPACENODE']._serialized_end=279
# @@protoc_insertion_point(module_scope)
