package(default_visibility = ["//visibility:public"])

cc_library(
    name = "hasher_lib",
    srcs = ["expression_hasher.cc"],
    hdrs = ["expression_hasher.h"],
    includes = ["."],
    deps = [
        "@mbedtls//:mbedtls",
    ]
)
