load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "com_github_grpc_grpc",
    strip_prefix = "grpc-tags-v1.63.0",
    urls = ["https://github.com/grpc/grpc/archive/tags/v1.63.0.tar.gz"],
)

http_archive(
    name = "com_github_singnet_das_proto",
    strip_prefix = "das-proto-0.1.13",
    urls = ["https://github.com/singnet/das-proto/archive/refs/tags/0.1.13.tar.gz"],
)

http_archive(
    name = "com_github_singnet_das_node",
    strip_prefix = "das-node-ab-test-1",
    urls = ["https://github.com/singnet/das-node/archive/refs/tags/ab-test-1.tar.gz"],
)

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()
load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")
grpc_extra_deps()

http_archive(
    name = "com_github_google_googletest",
    strip_prefix = "googletest-1.14.0",
    urls = ["https://github.com/google/googletest/archive/refs/tags/v1.14.0.tar.gz"]
)

new_local_repository(
    name = "mbedcrypto",
    path = "/opt/3rd-party/mbedcrypto",
    build_file_content = '\
cc_library(\
    name = "lib",\
    srcs = ["libmbedcrypto.a"],\
    visibility = ["//visibility:public"],\
)\
'
)

load("@rules_python//python:pip.bzl", "pip_parse")
# Create a central repo that knows about the dependencies needed from
# requirements.lock.txt.
pip_parse(
   name = "python_deps",
   requirements_lock = "//python/deps:requirements.lock.txt",
)
# Load the starlark macro, which will define your dependencies.
load("@python_deps//:requirements.bzl", "install_deps")
# Call it to define repos for your requirements.
install_deps()
