# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: attention-broker.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import hyperon_das.grpc.common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x16\x61ttention-broker.proto\x12\x08\x64\x61sproto\x1a\x0c\x63ommon.proto"Z\n\nHandleList\x12\x0c\n\x04list\x18\x01 \x03(\t\x12\x14\n\x0crequest_type\x18\x02 \x01(\x05\x12\x17\n\x0fhebbian_network\x18\x03 \x01(\x03\x12\x0f\n\x07\x63ontext\x18\x04 \x01(\t"\xa6\x01\n\x0bHandleCount\x12+\n\x03map\x18\x01 \x03(\x0b\x32\x1e.dasproto.HandleCount.MapEntry\x12\x14\n\x0crequest_type\x18\x02 \x01(\x05\x12\x17\n\x0fhebbian_network\x18\x03 \x01(\x03\x12\x0f\n\x07\x63ontext\x18\x04 \x01(\t\x1a*\n\x08MapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01"\x1e\n\x0eImportanceList\x12\x0c\n\x04list\x18\x01 \x03(\x02\x32\xe8\x01\n\x0f\x41ttentionBroker\x12(\n\x04ping\x12\x0f.dasproto.Empty\x1a\r.dasproto.Ack"\x00\x12\x33\n\tstimulate\x12\x15.dasproto.HandleCount\x1a\r.dasproto.Ack"\x00\x12\x32\n\tcorrelate\x12\x14.dasproto.HandleList\x1a\r.dasproto.Ack"\x00\x12\x42\n\x0eget_importance\x12\x14.dasproto.HandleList\x1a\x18.dasproto.ImportanceList"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "attention_broker_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_HANDLECOUNT_MAPENTRY"]._options = None
    _globals["_HANDLECOUNT_MAPENTRY"]._serialized_options = b"8\001"
    _globals["_HANDLELIST"]._serialized_start = 50
    _globals["_HANDLELIST"]._serialized_end = 140
    _globals["_HANDLECOUNT"]._serialized_start = 143
    _globals["_HANDLECOUNT"]._serialized_end = 309
    _globals["_HANDLECOUNT_MAPENTRY"]._serialized_start = 267
    _globals["_HANDLECOUNT_MAPENTRY"]._serialized_end = 309
    _globals["_IMPORTANCELIST"]._serialized_start = 311
    _globals["_IMPORTANCELIST"]._serialized_end = 341
    _globals["_ATTENTIONBROKER"]._serialized_start = 344
    _globals["_ATTENTIONBROKER"]._serialized_end = 576
# @@protoc_insertion_point(module_scope)
