# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: attention-broker.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import hyperon_das.grpc.common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61ttention-broker.proto\x12\x08\x64\x61sproto\x1a\x0c\x63ommon.proto2\xe8\x01\n\x0f\x41ttentionBroker\x12(\n\x04ping\x12\x0f.dasproto.Empty\x1a\r.dasproto.Ack\"\x00\x12\x33\n\tstimulate\x12\x15.dasproto.HandleCount\x1a\r.dasproto.Ack\"\x00\x12\x32\n\tcorrelate\x12\x14.dasproto.HandleList\x1a\r.dasproto.Ack\"\x00\x12\x42\n\x0eget_importance\x12\x14.dasproto.HandleList\x1a\x18.dasproto.ImportanceList\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'attention_broker_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ATTENTIONBROKER']._serialized_start=51
  _globals['_ATTENTIONBROKER']._serialized_end=283
# @@protoc_insertion_point(module_scope)