FROM python:3.11-slim-bullseye

ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

RUN addgroup --system appgroup \
    && adduser --system --ingroup appgroup appuser

RUN pip install --upgrade pip \
    && pip install requests

WORKDIR /app
COPY /src/scripts/mork_loader.py .

USER appuser

ENTRYPOINT ["python", "mork_loader.py"]
