---
name: Versioning

on:
  workflow_call:
    inputs:
      job-image-namespace:
        description: "Job image namespace"
        required: false
        type: string
      job-image-version-semver:
        description: "Job image version (semver)"
        required: false
        type: string
      main-branch:
        description: "Main branch"
        required: false
        type: string
      version-tag-regex-pattern:
        description: "Version tag regex pattern"
        required: false
        type: string
      version-strategy:
        description: "Version strategy"
        required: false
        default: "none"
        type: string
      version-require-confirmation:
        description: "Version require confirmation"
        required: false
        type: string
      version:
        description: "Version variable name"
        required: false
        type: string
      library:
        description: "Library's name"
        required: false
        type: string
      changelog:
        description: "Changelog"
        required: false
        type: string
        default: CHANGELOG
    secrets:
      MATTERMOST_WEBHOOK_URL:
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      release-note: ${{ steps.setup-release-note.outputs.releaseNote }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: setup-release-note
        name: Setup release notes
        run: |-
          releaseNote=$([ -e "${{ inputs.changelog }}" ] && awk -v ORS='\\n' '1' "${{ inputs.changelog }}" || echo "")
          echo "::set-output name=releaseNote::${releaseNote}"

  tag:
    runs-on: ubuntu-latest
    needs: setup
    container:
      image: "${{ inputs.job-image-namespace }}/das:${{ inputs.job-image-version-semver }}"
      env:
        JOB_IMAGE_VERSION_SEMVER: ${{ inputs.job-image-version-semver }}
        MAIN_BRANCH: ${{ inputs.main-branch }}
        VERSION_STRATEGY: ${{ inputs.version-strategy }}
        VERSION_REQUIRE_CONFIRMATION: ${{ inputs.version-require-confirmation }}
        VERSION_VARIABLE_NAME: VERSION
        VERSION: ${{ inputs.version }}
        VERSION_TAG_REGEX_PATTERN: ${{ inputs.version-tag-regex-pattern }}
        GITHUB_ACTOR: ${{ github.GITHUB_ACTOR }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_SERVER: github.com
        GITHUB_REPOSITORY: ${{ github.GITHUB_REPOSITORY }}
        GITHUB_USER_NAME: levisingularity
        GITHUB_USER_EMAIL: rafael.levi@singularitynet.io
        GITHUB_REF_NAME: ${{ github.GITHUB_REF_NAME }}
        GITHUB_SHA: ${{ github.GITHUB_SHA }}
        GITHUB_WORKFLOW: ${{ github.GITHUB_WORKFLOW }}
        CHANGELOG_PATH: ${{ inputs.changelog }}
    outputs:
      release-note: ${{ steps.semantic-versioning.outputs.ReleaseNote }}
      version: ${{ steps.semantic-versioning.outputs.NextPatchTag }}
      repository: ${{ steps.semantic-versioning.outputs.GITHUB_REPOSITORY }}
    steps:
      - id: semantic-versioning
        name: Semantic Versioning
        run: semantic-versioning.sh bump-version-from-variable-value

  notify-mattermost:
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create mattermost message
        run: |
          version="${{ needs.tag.outputs.version }}"
          repository="${{ needs.tag.outputs.repository }}"
          library="${{ inputs.library }}"
          releaseNote="${{ needs.tag.outputs.release-note }}"

          message=""

          if [ -n "$library" ]; then
            message="Library: $library\n\n"
          fi

          message="${message}New version available: $version\nRepository: https://github.com/$repository/releases/tag/$version"

          if [ -n "$releaseNote" ]; then
            message="$message\nChanges:\n$releaseNote"
          fi

          echo "{\"text\": \"$message\"}" > mattermost.json

      - name: Notify Mattermost
        uses: singnet/integration-github-mattermost@master
        with:
          webhook-url: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
