---
name: Daily Repository Check

on:
  schedule:
    - cron: "0 4 * * *"

  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/run-code-quality-and-tests-no-cache.yml

  notify-success:
    needs: ci
    if: success()
    runs-on: self-hosted
    steps:
      - name: Send success notification
        uses: singnet/integration-github-mattermost@v0.2.0
        with:
          webhook-url: ${{ secrets.SCHEDULED_REPOS_MATTERMOST_WEBHOOK_URL }}
          message: |
            SUCCESS - CI workflow succeeded in repository ${{ github.repository }}

  notify-failure:
    needs: ci
    if: failure()
    runs-on: self-hosted
    steps:
      - name: Send failure notification
        uses: singnet/integration-github-mattermost@v0.2.0
        with:
          webhook-url: ${{ secrets.SCHEDULED_REPOS_MATTERMOST_WEBHOOK_URL }}
          message: |
            FAILURE - CI workflow failed in repository ${{ github.repository }}

            Details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            ${{ needs.ci.outputs.failed_job != '' && format('Failed job: {0}', needs.ci.outputs.failed_job) || '' }}

            @channel
