name: On Issue Closed Update Project Card

on:
  workflow_call:
    inputs:
      repo:
        description: 'Repository name'
        required: true
        type: string
      owner:
        description: 'Repository owner'
        required: true
        type: string
      issue_number:
        description: 'Issue number'
        required: true
        type: number
      issue_name:
        description: 'Issue name'
        required: true
        type: string
      label_name:
        description: 'Label name to check for triggering the workflow'
        required: true
        type: string
      project_number:
        description: 'Project number to create the card in'
        required: true
        type: number
      target_column_name:
        description: 'Target column name in the project to move the card to'
        required: true
        type: string
      issue_labels:
        description: 'Labels to apply to the issue'
        required: false
        type: string
        default: '[]'
      issue_assignees:
        description: 'List of issue assignees. e.g. ["marcocapozzoli"]'
        required: false
        type: string
        default: '[]'

    secrets:
      GH_TOKEN:
        required: true

jobs:
  create-project-card:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set execute permission
        run: chmod +x scripts/on-issue-closed.sh

      - name: Update project card for documentation
        run: ./scripts/on-issue-closed.sh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: ${{ inputs.repo }}
          OWNER: ${{ inputs.owner }}
          ISSUE_NUMBER: ${{ inputs.issue_number }}
          LABEL_NAME: ${{ inputs.label_name }}
          PROJECT_NUMBER: ${{ inputs.project_number }}
          TARGET_COLUMN_NAME: ${{ inputs.target_column_name }}
          API_URL: "https://api.github.com"
          ISSUE_NAME: ${{ inputs.issue_name }}
          ISSUE_LABELS: ${{ inputs.issue_labels || '[]' }}
          ISSUE_ASSIGNEES: ${{ inputs.issue_assignees || '[]' }}
