name: Trigger Workflow on Issue Closed

on:
  issues:
    types: [closed]

jobs:
  trigger-workflow:
    if: contains(join(github.event.issue.labels.*.name, ','), 'Update docs')
    uses: singnet/das/.github/workflows/on-issue-closed-handler.yml@master
    with:
      repo: ${{ github.repository }}
      owner: ${{ github.repository_owner }}
      issue_number: ${{ github.event.issue.number }}
      label_name: 'Update docs'
      project_number: 6
      target_column_name: 'Update docs'
      issue_name: ${{ github.event.issue.title }}
      issue_labels: '["documentation"]'
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
