name: Build and Publish DAS

on:
  workflow_dispatch:

  workflow_call:

  push:
    branches:
      - master

jobs:
  compile-source-code:
    strategy:
      matrix:
        platforms: [amd64, arm64]
    runs-on:
      - ${{ matrix.platforms }}
      - self-hosted-withcache
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup bazel
        run: .github/scripts/setup_bazel.sh

      - name: Build Binaries
        run: .github/scripts/bazel_build.sh --binaries --arch=${{ matrix.platforms }}

      - name: Upload Binaries as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.platforms }}
          path: bin
          if-no-files-found: "error"

      - name: Upload libs Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libs-${{ matrix.platforms }}
          path: lib
          if-no-files-found: "error"

      - name: Extract DAS_VERSION from .bazelrc
        id: get_version
        run: |
          VERSION=$(grep -oP '(?<=--define=DAS_VERSION=)[0-9\.]+' src/.bazelrc)
          echo "DAS_VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if version already exists
        id: check_version
        run: |
          if git rev-parse "refs/tags/${{ steps.get_version.outputs.version }}" >/dev/null 2>&1; then
            echo "version_exists=true" >> $GITHUB_OUTPUT
          else
            echo "version_exists=false" >> $GITHUB_OUTPUT
          fi

    outputs:
      version: ${{steps.get_version.outputs.version}}
      version_exists: ${{steps.check_version.outputs.version_exists}}

  tag:
    needs: compile-source-code
    uses: singnet/das/.github/workflows/run-semver.yml@master
    if: needs.compile-source-code.outputs.version_exists != 'true'
    with:
      version: ${{ needs.compile-source-code.outputs.version }}
      version-strategy: bump-version-from-variable-value
      job-image-namespace: trueagi
      job-image-version-semver: semantic-versioning
      main-branch: master
      version-tag-regex-pattern: /^\d+\.\d+\.\d+$/
      version-require-confirmation: "true"
      title: New DAS version released
      deliverable: Tagged branch (${{ github.ref_name }}) in the repository
    secrets: inherit

  build-push-docker-image:
    strategy:
      matrix:
        platforms: [arm64, amd64]
    runs-on:
      - ${{ matrix.platforms }}
    if: needs.compile-source-code.outputs.version_exists != 'true'
    needs: compile-source-code
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Binaries Artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries-${{ matrix.platforms }}
          path: bin

      - name: Download lib Artifacts
        uses: actions/download-artifact@v4
        with:
          name: libs-${{ matrix.platforms }}
          path: lib

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.platforms }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .docker/poc/Dockerfile
          push: true
          platforms: ${{ matrix.platforms }}
          provenance: false
          tags: trueagi/das:${{ matrix.platforms }}

  publish-docker-image-manifest:
    runs-on: self-hosted
    needs:
      - build-push-docker-image
      - compile-source-code
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create docker manifest
        run: |
          docker manifest create trueagi/das:latest \
          --amend trueagi/das:amd64-rc \
          --amend trueagi/das:arm64-rc

      - name: Publish manifest
        run: docker manifest push trueagi/das:${{ needs.compile-source-code.outputs.version }}-rc
