name: Build and Publish POC Components

on:
  push:
    branches:
      - master
      - das-237

jobs:
  build-binaries:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Binaries
        run: |
          docker run --rm \
            -e CPP_WORKSPACE_DIR=/opt/das/cpp \
            -e PYTHON_WORKSPACE_DIR=/opt/das/python \
            -v $(pwd)/src/bin:/opt/das/bin \
            trueagi/das:22.04-builder \
            /usr/local/bin/bazel_build.sh --binaries

      - name: Upload Binaries as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: src/bin

  build_and_publish:
    runs-on: self-hosted
    needs: build-binaries
    strategy:
      matrix:
        target: [attention-broker, query-agent, link-creation-agent, link-creation-client]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Binaries Artifacts
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: src/bin

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .docker/poc/Dockerfile
          push: true
          target: ${{ matrix.target }}
          tags: trueagi/das:${{ matrix.target }}-poc
