---
name: Publish Hyperon DAS Commons to Pypi

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

jobs:
  tag:
    if: github.ref == 'refs/heads/master'
    uses: singnet/das/.github/workflows/run-semver.yml@master
    with:
      version: ${{ github.event.inputs.version }}
      version-strategy: bump-version-from-variable-value
      job-image-namespace: trueagi
      job-image-version-semver: semantic-versioning
      main-branch: master
      version-tag-regex-pattern: /^\d+\.\d+\.\d+$/
      version-require-confirmation: "true"
      title: New version of hyperon-das-commons
      deliverable: Library in PyPI named hyperon-das-commons
    secrets: inherit

  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    defaults:
      run:
        working-directory: ./python
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ^3.10

      - name: Install Poetry
        run: |
          pip install poetry
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}

      - name: Build and Publishing library version in PyPI
        run: |
          poetry version ${{ github.event.inputs.version }}
          poetry build
          poetry publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
