---
name: Publish DAS

on:
  push:
    branches:
      - docs/query-engine-mkdocs

jobs:
  publish-query-engine-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Query Engine Repo
        uses: actions/checkout@v4
        with:
          repository: singnet/das-query-engine
          token: ${{ secrets.GH_TOKEN }}
          ref: master

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: das

      - name: Merge 'docs' from DAS to Query Engine Repo
        run: |
          rsync -a das/docs/ ./docs/
          rsync -a das/mkdocs.yml ./

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: das

      - name: Merge 'docs' from DAS to Query Engine Repo
        run: |
          rsync -a das/docs/ ./docs/
          rsync -a das/mkdocs.yml ./

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ^3.10

      - name: Install Requirements
        run: pip install pymdown-extensions==10.8.1 mkdocs-material==9.5.13 mkdocstrings==0.24.1 mkdocstrings-python==1.8.0 griffe

      - name: Update Documentation
        run: mkdocs gh-deploy --force
