name: Run format check

on:
  workflow_call:
  workflow_dispatch:

jobs:
  format-check:
    runs-on:
      - self-hosted-withcache
      - ${{ github.actor }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bazel
        run: .github/scripts/setup_bazel.sh

      - name: Run format check
        working-directory: ./src
        run: |
          BAZELISK_HOME="$HOME/.cache/das/bazelisk" ./scripts/bazel_exec.sh --output_user_root="$HOME/.cache/das/bazel" run //:format.check
