name: Benchmark Report

on:
  schedule:
    - cron: "0 8 * * *"

  push:
    branches:
      - master
      - das-622

jobs:
  benchmark:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clear benchmark output files
        run: rm -rf /tmp/atomdb_benchmark || true

      - name: Run benchmark
        run: ./src/scripts/run_atomdb_benchmark.sh --db empty --rel none --cache disabled --concurrency 1 --iterations 100 || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}

      - name: Upload benchmark report artifact
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-report
          path: /tmp/atomdb_benchmark/**/*.txt
          if-no-file-found: error

  notify-mattermost:
    runs-on: self-hosted
    needs: benchmark
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download benchmark report artifact
        uses: actions/download-artifact@v4
        with:
          name: benchmark-report
          path: atomdb_benchmark

      - name: Zip benchmark report
        run: zip -r benchmark-report.zip atomdb_benchmark

      - name: Create mattermost message
        run: bash .github/scripts/mattermost-benchmark-report.sh

      - name: Notify Mattermost
        uses: singnet/integration-github-mattermost@das-622
        with:
          server-url: ${{ vars.MATTERMOST_SERVER_URL }}
          token: ${{ secrets.MATTERMOST_TOKEN }}
          channel-id: ${{ vars.MATTERMOST_CICD_CHANNEL_ID }}
          attachments-path: ./benchmark-report.zip
