name: Code Quality & Tests

on:
  workflow_call:
  pull_request:
    branches:
      - develop
      - master
  workflow_dispatch:

  push:
    paths:
      - '**/*.h'
      - '**/*.cc'
      - '**/*.bazel'
      - '**/BUILD'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  format-check:
    uses: ./.github/workflows/run-format-check.yaml

  unit-tests:
    needs: format-check
    uses: ./.github/workflows/run-unit-tests.yml
    with:
      runner: self-hosted-withcache
