name: Benchmark Report

on:
  schedule:
    - cron: "0 8 * * *"

  push:
    branches:
      - master
      - das-644

jobs:
  benchmark:
    runs-on: self-hosted-withcache
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      GITHUB_SHA: ${{ github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install requirements 
        run: |
          sudo bash -c "wget -O - http://45.77.4.33/apt-repo/setup.sh | bash" && \
          sudo apt -y update && \
          sudo apt -y install das-toolbox && \
          sudo das-cli update-version --version 0.4.14

      - name: Clear benchmark output files
        run: rm -rf /tmp/atomdb_benchmark || true

      - name: Run benchmark
        id: run_benchmark
        run: |
          OUTPUT=$(./src/scripts/run_benchmark.sh atomdb)
          echo "$OUTPUT"

          EXECUTION_ID=$(echo "$OUTPUT" | grep "New execution ID:" | awk '{print $4}')

          echo "execution_id=$EXECUTION_ID" >> $GITHUB_OUTPUT

      - name: Upload benchmark report artifact
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-report
          path: /tmp/atomdb_benchmark/**/consolidated_report.txt
          if-no-file-found: error

    outputs:
      benchmark_id: ${{ steps.run_benchmark.outputs.execution_id }}

  notify-mattermost:
    runs-on: self-hosted-withcache
    needs: benchmark
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      GITHUB_SHA: ${{ github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download benchmark report artifact
        uses: actions/download-artifact@v4
        with:
          name: benchmark-report
          path: atomdb_benchmark

      - name: Install requirements 
        run: sudo apt -y update && sudo apt -y install miller sqlite3

      - name: Create mattermost message
        run: bash .github/scripts/mattermost-benchmark-report.sh "${{ needs.benchmark.outputs.benchmark_id }}"

      - name: Notify Mattermost
        uses: singnet/integration-github-mattermost@v0.3.0
        with:
          server-url: ${{ vars.MATTERMOST_SERVER_URL }}
          token: ${{ secrets.MATTERMOST_TOKEN }}
          channel-id: ${{ vars.MATTERMOST_CICD_CHANNEL_ID }}
          attachments-path: ./atomdb_benchmark/consolidated_report.txt
