name: Code Quality & Tests Without Cache

on:
  workflow_call:
  workflow_dispatch:

jobs:
  format-check:
    uses: ./.github/workflows/run-format-check.yaml

  unit-tests:
    needs: format-check
    uses: ./.github/workflows/run-unit-tests.yml
    with:
      runner: self-hosted-nocache