name: Run Unit & Integration tests

on:
  workflow_call:
  pull_request:
    branches:
      - develop
      - master
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: self-hosted
    env:
      DAS_REDIS_HOSTNAME: localhost
      DAS_REDIS_PORT: 29000
      DAS_MONGODB_HOSTNAME: localhost
      DAS_MONGODB_PORT: 28000
      DAS_MONGODB_USERNAME: dbadmin
      DAS_MONGODB_PASSWORD: dassecret
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |-
          sudo apt -y update
          sudo apt -y install build-essential wget
          sudo bash -c "wget -O - http://45.77.4.33/apt-repo/setup.sh | bash"
          sudo apt install das-cli
          sudo das-cli update-version --version ${{ vars.DAS_CLI_VERSION }}
          das-cli --version

      - name: Download Knowledge Base
        run: curl https://raw.githubusercontent.com/singnet/das-toolbox/refs/heads/master/das-cli/src/examples/data/animals.metta -o /tmp/animals.metta

      - name: Setting das-cli configuration
        run: |-
          das-cli config set <<EOF
          $DAS_REDIS_PORT
          n
          $DAS_MONGODB_PORT
          $DAS_MONGODB_USERNAME
          $DAS_MONGODB_PASSWORD
          n
          8888
          37007
          35500
          9070
          EOF

      - name: Starting Redis and MongoDB
        run: das-cli db start

      - name: Load Knowledge Base
        run: das-cli metta load /tmp/animals.metta

      - name: Build source code
        run: make build-all

      - name: Starting Attention Broker
        run: make run-attention-broker &

      - name: Execute Unit Test Suite
        run: make test-all

  performance-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y pv

      - name: Build all targets
        run: make build-all

      - name: Start MongoDB and Redis
        run: sudo bash ./src/tests/integration/performance/start_mongo_and_redis.sh

      - name: Run performance tests
        run: make performance-tests

      - name: Get latest performance result file
        id: get-performance-result
        run: |
          FILE=$(ls -t ./src/tests/integration/performance/performance_results_*.txt | head -n 1)
          echo "Latest file: $FILE"
  
          CONTENT=$(cat "$FILE")
  
          ESCAPED_CONTENT="${CONTENT//$'\n'/\\n}"
  
          echo "content=$ESCAPED_CONTENT" >> $GITHUB_OUTPUT

      - name: Send success notification
        if: steps.get-performance-result.outputs.content != ''
        uses: singnet/integration-github-mattermost@master
        with:
          webhook-url: ${{ secrets.SCHEDULED_REPOS_MATTERMOST_WEBHOOK_URL }}
          message: |
            PERFORMANCE TEST - ${{ matrix.repo.name }}

            ${{ steps.get-performance-result.outputs.content }} 
